repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/mmacpherson/pre-commit-julia
    rev: b45d9de5d7d660414bbac1ba540c01b4cc230757
    hooks:
      - id: format_julia
